import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { AnnexureContext } from "@/lib/annexures/data";
import { Letterhead, SignatureLine, styles, PdfFooter } from "./shared";

/**
 * "Name and List of Equipments and Machinery along with the number, installed
 * capacity and horsepower used" — one of the manufacturer checklist items
 * (docs/FINDINGS.md), built straight from the equipment section.
 */
export function EquipmentList({ data }: { data: AnnexureContext }) {
  return (
    <Document
      title={`List of Equipment and Machinery — ${data.applicationNo}`}
      author="FoodRaksha"
      creator="FoodRaksha"
      producer="FoodRaksha"
      creationDate={data.documentDate}
      modificationDate={data.documentDate}
    >
      <Page size="A4" style={styles.page}>
        <Letterhead letterhead={data.letterhead} />

        <Text style={styles.title}>
          List of Equipment and Machinery with Installed Capacity
        </Text>
        <Text style={[styles.centred, styles.small]}>
          {data.business.legalName} · {data.premisesAddress}
        </Text>

        <View style={styles.table}>
          <View style={styles.tr}>
            <Text style={[styles.th, { width: "8%" }]}>Sl no.</Text>
            <Text style={[styles.th, { width: "44%" }]}>
              Name of equipment / machinery
            </Text>
            <Text style={[styles.th, { width: "16%" }]}>Number</Text>
            <Text style={[styles.th, { width: "32%" }]}>
              Capacity / horsepower
            </Text>
          </View>

          {data.equipment.map((item, index) => (
            <View key={`${item.name}-${index}`} style={styles.tr}>
              <Text style={[styles.td, { width: "8%" }]}>{index + 1}.</Text>
              <Text style={[styles.td, { width: "44%" }]}>{item.name}</Text>
              <Text style={[styles.td, { width: "16%" }]}>{item.quantity}</Text>
              <Text style={[styles.td, { width: "32%" }]}>{item.capacity}</Text>
            </View>
          ))}
        </View>

        <Text style={{ marginTop: 14 }}>
          <Text style={styles.bold}>
            Total installed capacity of the unit:{" "}
          </Text>
          {data.installedCapacity}
        </Text>
        <Text style={{ marginTop: 6 }}>
          <Text style={styles.bold}>Source of water: </Text>
          {data.waterSource}
        </Text>

        <View style={{ marginTop: 34, alignItems: "flex-end" }}>
          <SignatureLine
            signature={data.signature}
            caption="Signature of the authorised signatory"
          />
        </View>

        <View style={{ marginTop: 20 }}>
          <Text>Place: {data.place}</Text>
          <Text style={{ marginTop: 6 }}>Date: {data.date}</Text>
        </View>

        <PdfFooter>
          {data.applicationNo} · Equipment and machinery · generated by
          FoodRaksha
        </PdfFooter>
      </Page>
    </Document>
  );
}
