import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { AnnexureContext } from "@/lib/annexures/data";
import { SignatureLine, styles } from "./shared";

/**
 * FORM NO. IX — Form of Nomination, rule 2.5.1.
 *
 * The body text is reproduced verbatim from the official PDF in
 * docs/forms/FORM_IX.pdf, including its typographical quirks ("gives notice",
 * "persons(s)"). It is a statutory format: it is not ours to tidy up.
 */
export function FormIX({ data }: { data: AnnexureContext }) {
  const rows = Math.max(3, data.nominees.length);

  return (
    <Document
      title={`Form IX — ${data.applicationNo}`}
      author="FoodRaksha"
      creator="FoodRaksha"
      producer="FoodRaksha"
      creationDate={data.documentDate}
      modificationDate={data.documentDate}
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>FORM NO.IX</Text>
        <Text style={styles.subtitle}>
          (Form of Nomination – Refer rule 2.5.1)
        </Text>
        <Text style={styles.centred}>NOMINATION OF PERSONS BY A COMPANY</Text>

        <Text style={styles.paragraph}>
          Being the proprietor or a signatory authorized by the board of
          directors of the company in terms of Rule 2.5.1 (2), I do hereby gives
          notice that the following persons(s) is/are nominated as the person(s)
          in charge of establishment, branch or the unit mentioned against the
          name of the person(s) and shall be responsible and liable for food
          safety or any contravention of the Act and rules/regulations or
          directions issued thereunder in respect of the concerned
          establishment/branch/unit. The person(s) shall take all such steps as
          may be necessary to prevent the commission by the Company of any
          offence under and comply with the provisions of Food Safety and
          Standards Act, 2006 and the Rules and Regulations made thereunder.
        </Text>

        <Text style={{ marginBottom: 10 }}>
          Branch wise/office wise nomination .
        </Text>

        <View style={styles.betweenRow}>
          <Text style={{ width: "48%" }}>Establishment/branch/unit name</Text>
          <Text style={{ width: "48%" }}>Name and Sign of Person i/c</Text>
        </View>

        {Array.from({ length: rows }).map((_, index) => {
          const nominee = data.nominees[index];
          return (
            <View
              key={index}
              style={{ flexDirection: "row", marginTop: 12, gap: 8 }}
            >
              <View style={{ width: "48%" }}>
                <Text>
                  {index + 1}.{" "}
                  {nominee
                    ? `${data.business.tradeName} — ${data.premisesAddress}`
                    : ""}
                </Text>
              </View>
              <View style={{ width: "48%" }}>
                <Text>
                  {index + 1}. {nominee ? nominee.name : ""}
                </Text>
                {nominee && (
                  <>
                    <Text style={styles.small}>{nominee.designation}</Text>
                    <Text style={styles.small}>{nominee.address}</Text>
                  </>
                )}
              </View>
            </View>
          );
        })}

        <View style={{ height: 24 }} />

        <Text>
          A certified copy of the resolution of the board regarding the
          authorized
        </Text>
        <Text style={{ marginTop: 6 }}>
          signatory, dated ______ is enclosed.
        </Text>

        <View style={{ height: 28 }} />

        <View style={styles.betweenRow}>
          <View>
            <Text>Place: {data.place}</Text>
            <Text style={{ marginTop: 8 }}>Date: {data.date}</Text>
          </View>
          <View style={{ width: "50%" }}>
            <Text>For {data.business.legalName}</Text>
            <View style={{ marginTop: 10 }}>
              <SignatureLine
                signature={data.signature}
                caption="1. Authorized signatory of the company"
              />
            </View>
          </View>
        </View>

        <View style={{ height: 20 }} />
        <Text>Place: {data.place}</Text>
        <Text style={{ marginTop: 6 }}>Date: {data.date}</Text>

        <Text style={styles.footerNote} fixed>
          {data.applicationNo} · Form IX · generated by FoodRaksha
        </Text>
      </Page>
    </Document>
  );
}
