import { Document, Page, Text, View } from "@react-pdf/renderer";
import type { AnnexureContext } from "@/lib/annexures/data";
import { Letterhead, SignatureLine, styles, PdfFooter } from "./shared";

/**
 * Recall Plan, required of manufacturers.
 *
 * The business-specific facts come from the questionnaire; the procedure is
 * FoodRaksha's standard plan, which staff can edit in the generated document
 * before filing if a unit works differently.
 */
const STEPS: { heading: string; body: (data: AnnexureContext) => string }[] = [
  {
    heading: "1. Purpose and scope",
    body: (data) =>
      `This plan sets out how ${data.business.legalName} identifies, withdraws and accounts for any food it has placed on the market that may be unsafe, unfit or misdescribed. It covers every product handled at ${data.premisesAddress}.`,
  },
  {
    heading: "2. Recall team",
    body: (data) =>
      `${data.applicant.name} (${data.applicant.designation}) leads any recall and is the single point of contact for the Food Safety Officer, on ${data.applicant.mobile}. In their absence the person nominated under Form IX takes charge.`,
  },
  {
    heading: "3. Traceability records",
    body: () =>
      "Batch or lot codes, production dates, quantities produced, and the name and address of every buyer are recorded for each despatch and kept for at least one year beyond the shelf life of the product. Records identify one step back to the supplier and one step forward to the buyer.",
  },
  {
    heading: "4. Deciding on a recall",
    body: () =>
      "On any complaint, adverse test result or regulatory direction indicating a food safety risk, the recall team assesses the hazard, the batches affected and the distribution already made, and decides within 24 hours whether to withdraw the product from the trade or recall it from consumers.",
  },
  {
    heading: "5. Notification",
    body: () =>
      "The Designated Officer and the Commissioner of Food Safety are informed immediately, in writing, with the product name, batch codes, quantity, nature of the risk and the distribution list. Public notice is issued where the product has reached consumers.",
  },
  {
    heading: "6. Retrieval and disposal",
    body: () =>
      "Recovered stock is quarantined, physically separated and clearly marked. It is reconciled against the quantity despatched, and disposed of or reprocessed only with the written approval of the Food Safety Officer.",
  },
  {
    heading: "7. Review",
    body: () =>
      "The plan is mock-tested once a year and reviewed after any recall, and the results are recorded.",
  },
];

export function RecallPlan({ data }: { data: AnnexureContext }) {
  return (
    <Document
      title={`Recall Plan — ${data.applicationNo}`}
      author="FoodRaksha"
      creator="FoodRaksha"
      producer="FoodRaksha"
      creationDate={data.documentDate}
      modificationDate={data.documentDate}
    >
      <Page size="A4" style={styles.page}>
        <Letterhead letterhead={data.letterhead} />

        <Text style={styles.title}>Product Recall Plan</Text>
        <Text style={[styles.centred, styles.small]}>
          Food Safety and Standards (Food Recall Procedure) Regulations, 2017
        </Text>

        {data.foodCategories.length > 0 && (
          <Text style={{ marginBottom: 10 }}>
            <Text style={styles.bold}>Food categories handled: </Text>
            {data.foodCategories.join("; ")}
          </Text>
        )}

        {STEPS.map((step) => (
          <View key={step.heading} style={{ marginBottom: 10 }}>
            <Text style={styles.bold}>{step.heading}</Text>
            <Text style={{ textAlign: "justify" }}>{step.body(data)}</Text>
          </View>
        ))}

        <View style={{ marginTop: 26, alignItems: "flex-end" }}>
          <SignatureLine
            signature={data.signature}
            caption="Signature of the authorised signatory"
          />
        </View>

        <View style={{ marginTop: 20 }}>
          <Text>Place: {data.place}</Text>
          <Text style={{ marginTop: 6 }}>Date: {data.date}</Text>
        </View>

        <PdfFooter>
          {data.applicationNo} · Recall plan · generated by FoodRaksha
        </PdfFooter>
      </Page>
    </Document>
  );
}
